cask_args appdir: "/Applications"

tap "codeclimate/formulae"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "kryptco/tap"
tap "nektos/tap"
tap "puma/puma"
tap "raggi/ale"

# brew "cairo"
# brew "cowsay"
# brew "doxygen"
# brew "fd"
# brew "figlet"
# brew "forego"
# brew "gdbm"
# brew "git-cal"
# brew "git-flow"
# brew "gmp"
# brew "jbig2dec"
# brew "libxml2"
# brew "mycli"
# brew "ossp-uuid"
# brew "pgformatter"
# brew "pkg-config"
# brew "pv"
# brew "reattach-to-user-namespace"
# brew "ruby", link: true
# brew "the_silver_searcher"
# brew "utf8proc"
# brew "watchman"
# brew "wxmac"
# brew "xz"

brew "autoconf"
brew "awscli"
brew "bash-completion"
brew "bat"
brew "cmake"
brew "crystal"
brew "cscope"
brew "ctags"
brew "diff-so-fancy"
brew "direnv"
brew "editorconfig"
brew "elixir"
brew "fzf"
brew "geckodriver"
brew "ghostscript"
brew "git"
brew "go"
brew "htop"
brew "hub"
brew "imagemagick"
brew "jq"
brew "kryptco/tap/kr"
brew "leiningen"
brew "libffi"
brew "libtool"
brew "memcached"
brew "nektos/tap/act"
brew "neovim"
brew "nginx"
brew "nodenv"
brew "noti"
brew "perl"
brew "pgformatter"
brew "pick"
brew "postgresql"
brew "pstree"
brew "puma/puma/puma-dev"
brew "pyenv"
brew "pyenv-virtualenv"
brew "raggi/ale/openssl-osx-ca"
brew "rbenv"
brew "redis"
brew "ripgrep"
brew "ruby-build"
brew "shellcheck"
brew "terminal-notifier"
brew "tmux"
brew "vim"
brew "wget"
brew "yarn"

cask "google-cloud-sdk"
cask "ngrok"
cask "homebrew/cask-fonts/font-meslo-for-powerline"
